### PR TITLE
[#31] Use sentry-sdk client

### LINKED ISSUE #31: Use the new Sentry SDK
[Raven](https://github.com/getsentry/raven-python) is being phased out in favor of the [Sentry SDK](https://github.com/getsentry/sentry-python). Are you planning to update the library to use that?

### PR DESCRIPTION
**Pull request by Siecje**
Fixes #31

### CODE REVIEW

**Comment by Siecje** [comment]
Thanks for merging this! Do you know when the next release will be?

**Comment by bittner** [comment]
@mdgart Why did you merge the PR when not even the linting passed? :worried:

**Comment by mdgart** [comment]
It's pylint and flake8 that is failing, but you are totally right, we need to fix that, I'll revert the merge.
@Siecje can you take a look why this is failing?

**Comment by bittner** [comment]
It's simple: There are a few issues to correct. The CI jobs show them all:

- [Too long lines, unused imports, whitespace](https://travis-ci.org/mdgart/sentrylogs/jobs/520439485#L210-L226) (flake8)
- [more or less the same things again](https://travis-ci.org/mdgart/sentrylogs/jobs/520439486#L211-L222) (Pylint)

**Comment by Siecje** [comment]
@bittner Thanks, I ran `tox` but the flake8 and pylint tests were already failing. I didn't know the tests were not being run in CI if they failed.

I've fixed the pylint and flake8 issues in https://github.com/mdgart/sentrylogs/pull/40

**Pull request merged**
