### PR TITLE
Handle FileNotFound and Permission errors gracefully

### PR DESCRIPTION
**Pull request by bittner**
Handle I/O errors when reading log files using exception handling.

### CODE REVIEW

**Comment by bittner** [comment]
@mdgart I'll test how well this is working on our infrastructure, and if it all goes well we can release a version 0.2.0 tomorrow, if you want.

Can you push releases to PyPI (do you have all set up on your machine)? I can also do that otherwise. You'd need to add me to the index owners [on PyPI](https://pypi.python.org/pypi/SentryLogs) though.

**Comment by mdgart** [comment]
I don't have anything setup on my machine, it's almost an year that
(unfortunately) I don't use python (we use Ruby and Scala where I work), so
feel free to do it.
How can I add you as owner to PyPI?

2016-06-09 15:31 GMT-07:00 Peter Bittner <notifications@github.com>:

**Comment by bittner** [comment]
You have to log in on PyPI (right upper corner) and then [edit the Roles](https://pypi.python.org/pypi?:action=role_form&package_name=SentryLogs) for the package. That should work.

**Comment by mdgart** [comment]
yeah, but I need your user name on PyPI

2016-06-09 16:49 GMT-07:00 Peter Bittner <notifications@github.com>:

**Comment by bittner** [comment]
Oh, sorry! It's `bittner`, as usual.  :smiley:

**Comment by mdgart** [comment]
Done!

2016-06-09 17:36 GMT-07:00 Peter Bittner <notifications@github.com>:

**Comment by bittner** [comment]
Thanks! -- I'll bump the version number and release v0.2.0. Everything else (bug fixes, features) can follow.

**Pull request merged**
