### PR TITLE
Make package better match standard practices, add static code analysis

### PR DESCRIPTION
**Pull request by bittner**
* Add tox configuration and static code analysis (flake8, pylint)
* Convert README to reStructuredText (was: MarkDown) for PyPI
* Add full text of license (identical to Sentry project)
* Use standard naming for contributors file
* Move package information to __init__ file
* Fix flake8 complaints (mainly white space changes)
* Fix PyLint complaints
* Fix potential IndexError (list index out of range)

### CODE REVIEW

**Comment by bittner** [comment]
Thanks for merging!

I'll add badges to the README tomorrow, and maybe so simple functional tests.

Can you open two accounts so that I can make the README show working badges?

- [ ] **Travis CI:** https://travis-ci.org/mdgart/sentrylogs (build server)
- [ ] **Landscape:** https://landscape.io/github/mdgart/sentrylogs (static code analysis)

Thanks again!

**Comment by mdgart** [comment]
Done, there is something else I have to do?

2016-06-07 15:27 GMT-07:00 Peter Bittner <notifications@github.com>:

**Comment by bittner** [comment]
Merge PR #11 please, then we're all set.

I'll add the tests for the Python versions and a Travis CI configuration tomorrow.

**Comment by mdgart** [comment]
Awesome, thanks so much for doing this, I don't use Sentry anymore but this
will be very good for other people that use it.

2016-06-07 16:02 GMT-07:00 Peter Bittner <notifications@github.com>:

**Comment by bittner** [comment]
You should start to use it again. It's getting better every day.

**Pull request merged**
